### PR TITLE
install mailcatcher, added config for dev

### PR DESCRIPTION
**Pull request by Kwasi008**
## Description
@jrmcgarvey 
- mailcatcher installation

### CODE REVIEW

**Comment by kidatsy** [comment]
that's all we need to use mailcatcher?

**Review by jrmcgarvey — CHANGES_REQUESTED** [review]
This PR doesn't make any sense.  We have config.action_mailer.delivery_method as sendgrid one place and smtp in another place right below it.  I think we want to use sendgrid, so we don't want this change -- unless perhaps we don't want to use sendgrid in development???

**Comment by Kwasi008** [comment]
Hi John I think at the moment we were unaware that we can use sendgrid for development, so we were looking into mailcatcher, I don't mind looking into sendgrid for development, whatever is best for the project. @kidatsy @jrmcgarvey

**Comment by jrmcgarvey** [comment]
Kwasi, mailcatcher is a separate process that is used to catch the mail.  One could use it instead of sendgrid.  The only advantage is that then you do not have to have valid email addresses for testing.  However, then you have to figure out how to get the mailcatcher gem loaded into the environment (you can't put it in the gemfile) and also how to get the separate mailcatcher process started in the environment (it doesn't run inside the Rails server).  

There is a curious inconsistency right now between config/environments/production.rb and config/environments/development.rb.  The production one has this stanza:

  config.action_mailer.smtp_settings = {
    address:              "smtp.gmail.com",
    port:                 587,
    domain:               "gmail.com",
    authentication:       "plain",
    enable_starttls_auto: true,
    user_name:            Rails.application.credentials[:GMAIL_USERNAME],
    password:             Rails.application.credentials[:GMAIL_PASSWORD]
  }

I think this is ignored in the environment because smtp is not being used to send the mail.  So this stanza should be removed, and there is no need to have GMAIL_USERNAME and GMAIL_PASSWORD in the credentials.yml.enc either.

So there is still a question -- what do we do for mail test?  Right now we have no test cases for mail, and we have no mail configuration at all in the config/environments/test.rb.  I don't know if this is something we need to fix.

Anyway, the code inside this PR should not be merged, as it conflicts with the sendgrid configuration we have.  I am closing this PR.

**Pull request closed without merging**
